# -*- coding: utf-8 -*-
"""multitrack_pitch_duration_flow_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrNdkE2yFeo9rTm1MyLlrhXBAAr621-6

# Multi-Track Pitch / Duration Flow Demo (SkyTNT midi-model)

This Colab-ready notebook:

1. Clones the **SkyTNT midi-model** repo and loads the `MidiModel` and `MIDITokenizerV2`.
2. Downloads a multi-track MIDI file and splits it into **per-track MIDI files**.
3. Computes **information content (IC)** per event using the model, and **separates** IC into:
   - pitch-only IC
   - duration-only IC
4. For each pair of tracks, merges them and computes **joint IC**.
5. Builds **flow matrices** for:
   - pitch-only flow
   - duration-only flow
   - joint (pitch + duration) flow
6. Visualizes the flow matrices.

## 1. Setup: install dependencies and clone midi-model
"""

!pip install -q miditoolkit pretty_midi matplotlib
!git clone https://github.com/SkyTNT/midi-model.git

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd midi-model

import torch
from midi_tokenizer import MIDITokenizerV2
from midi_model import MIDIModel

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = MIDIModel.from_pretrained('skytnt/midi-model-tv2o-medium').to(device)
model.eval()
tokenizer = model.config.tokenizer
print('Loaded model on', device)

!ls

"""## 2. Inspect tokenizer schema (note events, pitch, duration)"""

print("=== tokenizer.events ===")
for name, params in tokenizer.events.items():
    print(f"{name}: {params}")

print("\n=== tokenizer.parameter_ids (first 10 of each) ===")
for pname, ids in tokenizer.parameter_ids.items():
    print(f"{pname:10s}: {len(ids)} ids, first 10 = {ids[:10]}")

print("\n=== tokenizer.event_ids ===")
print(tokenizer.event_ids)

print("\n=== tokenizer.id_events (keys) ===")
print(list(tokenizer.id_events.keys())[:20])

"""## 3. Derive positions for note pitch / duration tokens"""

# We assume the 'note' event is defined as in your environment:
# note ['time1', 'time2', 'track', 'channel', 'pitch', 'velocity', 'duration']

note_params = tokenizer.events['note']  # list of parameter names for 'note' events

# Position 0 of a token row is the event type id, so parameters start at index 1
note_pitch_pos    = 1 + note_params.index('pitch')
note_duration_pos = 1 + note_params.index('duration')

note_type_id = tokenizer.event_ids['note']

print("Note params:", note_params)
print("note_type_id:", note_type_id)
print("Pitch token position:", note_pitch_pos)
print("Duration token position:", note_duration_pos)

"""## 4. Helper: MIDI → token sequence"""

def midi_path_to_tokens(path, tokenizer):
    """Convert a MIDI file path to a (L, T) numpy int64 token array using SkyTNT's tokenizer."""
    with open(path, "rb") as f:
        data = f.read()
    midi_score = MIDI.midi2score(data)
    seq = tokenizer.tokenize(midi_score)
    return np.asarray(seq, dtype=np.int64)

"""## 5. Compute IC components (all, pitch-only, duration-only)"""

def compute_ic_components(path):
    """
    Compute IC components for a single-track MIDI at `path`.

    Returns:
      ic_all:      np.array, IC per event (mean over all tokens in the event)
      ic_pitch:    np.array or None, IC for the pitch token of note events
      ic_duration: np.array or None, IC for the duration token of note events
      note_mask:   boolean np.array over events (same length as ic_all) indicating which are 'note'
    """
    tokens = midi_path_to_tokens(path, tokenizer)   # shape: (L, T)
    if tokens.shape[0] < 2:
        return np.array([]), None, None, None

    # Prepare input/target
    ids = torch.tensor(tokens, dtype=torch.long, device=device).unsqueeze(0)  # (1, L, T)

    with torch.no_grad():
        x = ids[:, :-1]   # prefix events (1, L-1, T)
        y = ids[:, 1:]    # target events (1, L-1, T)

        hidden = model(x)               # (1, L-1, D, ...)
        hidden = hidden.reshape(-1, hidden.shape[-1])  # (N, D)

        y_flat = y.reshape(-1, y.shape[-1])            # (N, T)
        x_tok  = y_flat[:, :-1]                        # (N, T-1), within-event prefix tokens

        # Predict tokens at positions 1..T-1
        logits = model.forward_token(hidden, x_tok)    # (N, T-1, vocab)
        log_probs = F.log_softmax(logits, dim=-1)      # (N, T-1, vocab)

        # Targets are the next tokens in y_flat
        target = y_flat[:, 1:].unsqueeze(-1)           # (N, T-1, 1)
        token_log_probs = log_probs.gather(-1, target).squeeze(-1)  # (N, T-1)

        # Build a "full" log-prob array of length T, padding position 0 (unused)
        pad_col = torch.zeros(token_log_probs.size(0), 1, device=token_log_probs.device)
        token_log_probs_full = torch.cat([pad_col, token_log_probs], dim=1)  # (N, T)

        # 1) Event-level IC (mean over all tokens in event)
        ic_all = -token_log_probs_full.mean(dim=-1).cpu().numpy()  # (N,)

        # 2) Note-only IC for pitch & duration
        event_type_ids = y_flat[:, 0]               # type token at position 0
        note_mask_t = (event_type_ids == note_type_id)  # boolean mask
        note_mask = note_mask_t.cpu().numpy().astype(bool)

        if note_mask.any():
            note_log_probs = token_log_probs_full[note_mask]  # (N_notes, T)

            pitch_lp    = note_log_probs[:, note_pitch_pos]
            duration_lp = note_log_probs[:, note_duration_pos]

            ic_pitch    = (-pitch_lp).cpu().numpy()
            ic_duration = (-duration_lp).cpu().numpy()
        else:
            ic_pitch = None
            ic_duration = None

    return ic_all, ic_pitch, ic_duration, note_mask

"""## 6. Download a multi-track MIDI and split into per-track files"""

import mido
from mido import MidiFile

#filename = "/content/chorales_026700b_(c)greentree.mid"
#filename = "/content/chorales_014007b_(c)greentree.mid"
#filename = "/content/chorales_024403b_(c)greentree.mid"
# filename = "/content/mozart_chamber_music_387_(c)harfesoft.mid"
filename = "/content/0_final_duet.mid"

mid = MidiFile(filename)
print("MIDI Type:", mid.type)
print("Tracks:", len(mid.tracks))

for i, track in enumerate(mid.tracks):
    print(f"Track {i}: {track.name}, messages={len(track)}")

from mido import MidiFile, MidiTrack
from google.colab import files
import os

# Make output directory
os.makedirs("tracks", exist_ok=True)
track_paths = []

# Pick which tracks contain the 4 voices:
voice_tracks = [1, 2]   # <-- adjust as needed

for i, idx in enumerate(voice_tracks, start=1):
    out = MidiFile(type=1)
    out.ticks_per_beat = mid.ticks_per_beat

    # Optional: keep metadata (tempo, key, markers) from track 0
    meta_track = MidiTrack()
    for msg in mid.tracks[0]:
        meta_track.append(msg.copy())
    out.tracks.append(meta_track)

    # Add ONLY the selected voice
    voice_track = MidiTrack()
    for msg in mid.tracks[idx]:
        voice_track.append(msg.copy())
    out.tracks.append(voice_track)

    # Save to tracks/ folder
    outname = f"tracks/track_{i}.mid"
    out.save(outname)
    track_paths.append(outname)

    print(f"Saved track {i} to {outname}")
    #files.download(outname)

"""## 7. Compute per-track ICs (all, pitch, duration)"""

import MIDI
import numpy as np
import torch.nn.functional as F

track_H_all = []
track_H_pitch = []
track_H_duration = []

for path in track_paths:
    print("\nTrack:", path)
    ic_all, ic_pitch, ic_duration, note_mask = compute_ic_components(path)

    H_all = float(np.mean(ic_all)) if ic_all.size else float("nan")
    H_pitch = float(np.mean(ic_pitch)) if (ic_pitch is not None and len(ic_pitch) > 0) else float("nan")
    H_duration = float(np.mean(ic_duration)) if (ic_duration is not None and len(ic_duration) > 0) else float("nan")

    print("  H_all     =", H_all)
    print("  H_pitch   =", H_pitch)
    print("  H_duration=", H_duration)

    track_H_all.append(H_all)
    track_H_pitch.append(H_pitch)
    track_H_duration.append(H_duration)

track_H_all = np.array(track_H_all)
track_H_pitch = np.array(track_H_pitch)
track_H_duration = np.array(track_H_duration)

"""## 8. Helper: merge two tracks into a temporary MIDI"""

def merge_two_tracks(path_i, path_j, out_path):
    """Merge two single-instrument MIDI files into one multi-track MIDI and save to out_path."""
    mi = miditoolkit.MidiFile(path_i)
    mj = miditoolkit.MidiFile(path_j)

    m = miditoolkit.MidiFile()
    m.ticks_per_beat = mi.ticks_per_beat
    m.tempo_changes = mi.tempo_changes
    m.time_signature_changes = mi.time_signature_changes

    # Append instruments from both
    m.instruments = []
    for inst in mi.instruments:
        m.instruments.append(deepcopy(inst))
    for inst in mj.instruments:
        m.instruments.append(deepcopy(inst))

    m.dump(out_path)
    #files.download(out_path)

"""## 9. Compute joint ICs and flow matrices (pitch, duration, joint)"""

import itertools
import miditoolkit
import math
from copy import deepcopy

n = len(track_paths)

joint_H_pitch = np.full((n, n), np.nan)
joint_H_duration = np.full((n, n), np.nan)
joint_H_joint = np.full((n, n), np.nan)  # combined pitch+duration

# Make directory for merged MIDI files
os.makedirs("merged", exist_ok=True)

for i, j in itertools.combinations(range(n), 2):

    merged_path = f"merged/merged_{i}_{j}.mid"
    merge_two_tracks(track_paths[i], track_paths[j], merged_path)

    ic_all_xy, ic_pitch_xy, ic_duration_xy, note_mask_xy = compute_ic_components(merged_path)

    H_pitch_xy = float(np.mean(ic_pitch_xy)) if (ic_pitch_xy is not None and len(ic_pitch_xy) > 0) else float("nan")
    H_duration_xy = float(np.mean(ic_duration_xy)) if (ic_duration_xy is not None and len(ic_duration_xy) > 0) else float("nan")

    if (ic_pitch_xy is not None) and (ic_duration_xy is not None) and len(ic_pitch_xy) > 0 and len(ic_duration_xy) > 0:
        H_joint_xy = float(np.mean(ic_pitch_xy + ic_duration_xy))
    else:
        H_joint_xy = float("nan")

    joint_H_pitch[i, j] = joint_H_pitch[j, i] = H_pitch_xy
    joint_H_duration[i, j] = joint_H_duration[j, i] = H_duration_xy
    joint_H_joint[i, j] = joint_H_joint[j, i] = H_joint_xy

# Build flow matrices: Flow(i,j) = H(i) + H(j) - H_ij
Flow_pitch = np.zeros((n, n))
Flow_duration = np.zeros((n, n))
Flow_joint = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        if i == j:
            Flow_pitch[i, j] = 0.0
            Flow_duration[i, j] = 0.0
            Flow_joint[i, j] = 0.0
            continue

        Hi_p, Hj_p = track_H_pitch[i], track_H_pitch[j]
        Hij_p = joint_H_pitch[i, j]

        Hi_d, Hj_d = track_H_duration[i], track_H_duration[j]
        Hij_d = joint_H_duration[i, j]

        Hi_j, Hj_j = Hi_p + Hi_d, Hj_p + Hj_d
        Hij_j = joint_H_joint[i, j]

        if not (math.isnan(Hi_p) or math.isnan(Hj_p) or math.isnan(Hij_p)):
            Flow_pitch[i, j] = Hi_p + Hj_p - Hij_p
        else:
            Flow_pitch[i, j] = float("nan")

        if not (math.isnan(Hi_d) or math.isnan(Hj_d) or math.isnan(Hij_d)):
            Flow_duration[i, j] = Hi_d + Hj_d - Hij_d
        else:
            Flow_duration[i, j] = float("nan")

        if not (math.isnan(Hi_j) or math.isnan(Hj_j) or math.isnan(Hij_j)):
            Flow_joint[i, j] = Hi_j + Hj_j - Hij_j
        else:
            Flow_joint[i, j] = float("nan")

Flow_pitch, Flow_duration, Flow_joint

"""## 10. Visualize flow matrices"""

import matplotlib.pyplot as plt

track_names = [f"Track {i}" for i in range(n)]

def plot_flow_matrix(M, title):
    plt.figure(figsize=(6,5))
    plt.imshow(np.log(M), cmap="viridis")
#   plt.imshow(M, cmap="viridis")
    plt.colorbar(label="Flow")
    plt.xticks(range(n), track_names, rotation=45)
    plt.yticks(range(n), track_names)
    plt.title(title)
    plt.tight_layout()
    plt.show()

plot_flow_matrix(Flow_pitch, "Pitch-only Flow")
plot_flow_matrix(Flow_duration, "Duration-only Flow")
plot_flow_matrix(Flow_joint, "Joint Pitch+Duration Flow")

Flow_pitch

